#!/usr/bin/env bash
set -Eeuo pipefail

declare -r archives='https://nstepien.github.io/archives.json/archives.json'
declare -r jsonfile='/tmp/archives.json'
declare -i start=1
declare -i total=1
declare -i last=1
declare -a threadlist
declare -a imagelist
declare folder="${HOME}/Downloads/4chan"
declare search='fglt'
declare board='g'
declare boardurl

while(($# > 0)); do
	case ${1} in
		-a) shift; start=${1?-a needs an integer} ;;
		-t) shift; total=${1?-t needs an integer} ;;
		-f) shift; folder=${1?-f needs a directory} ;;
		-s) shift; search=${1?-s needs an argument} ;;
		-b) shift; board=${1?-b needs an argument} ;;
		*) exit ;;
	esac
	shift
done

wget -q -N -O"${jsonfile}" -- "${archives}"
mkdir -p -- "${folder}/${board}"

boardurl=$(jq -r "first(.[] | select(.files[] == \"${board}\") | .domain)" -- "${jsonfile}")

[[ -z ${boardurl} ]] && { printf 'no archive for %q.\n' "${board}" >&2; exit 1; }
[[ -w ${folder} ]] || { printf '%q not writable.\n' "${folder}" >&2; exit 1; }

((last = start + --total))

mapfile -t threadlist < <(
	parallel --bar -j32 'wget -q -O/dev/stdout https://{1}/{2}/search/text/{3}/type/op/page/{4}/' ::: "${boardurl}" ::: "${board}" ::: "${search}" :::: <(seq "${start}" "${last}") |\
	grep -Eo "https?://${boardurl}/${board}/thread/[0-9]+/" |\
	sort -u
)

((${#threadlist[@]})) || { printf 'no threads for %q.\n' "${search}" >&2; exit 1; }
printf 'Found %d threads.\n' "${#threadlist[@]}"

mapfile -t imagelist < <(
	parallel --bar -j32 'wget -q -O/dev/stdout {1}' ::: "${threadlist[@]}" |\
	grep -Eo "[a-z0-9]+[a-zA-Z0-9\\/\\.-]+/image/[a-z0-9\\/]+\\.[a-z]{3,4}" |\
	sort -u
)

((${#imagelist[@]})) || { printf 'no images for %q.\n' "${search}" >&2; exit 1; }
printf 'Found %d images.\n' "${#imagelist[@]}"

parallel --bar -j32 'wget -q -nc -P{1} -- {2}' ::: "${folder}/${board}/" ::: "${imagelist[@]}"
